In [1]:
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv('Bank Churn dataset.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

## Dropping the first 3 columns as it is of no use for prediction.

In [3]:
data.drop(['RowNumber','CustomerId','Surname'],inplace=True,axis=1)
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [4]:
def print_unique_value(df):
    for column in df:
        if df[column].dtypes=='object':
            print(f'{column}:{df[column].unique()}')

    

In [5]:
print_unique_value(data)

Geography:['France' 'Spain' 'Germany']
Gender:['Female' 'Male']


In [6]:
data['Gender']=data['Gender'].replace({'Female':0,'Male':1})

In [7]:
data=pd.get_dummies(data=data,columns=['Geography'])

In [8]:
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   

   Geography_Germany  Geography_Spain  
0                  0                0  
1                  0                1  
2                  0                0  
3                  0                0  
4                  0                1

In [9]:
data.shape

(10000, 13)

In [10]:
x=data.drop('Exited',axis=1).values
y=data['Exited'].values

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.25)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [13]:
import tensorflow as tf
from tensorflow import keras
model=keras.models.Sequential([
    keras.layers.Dense(6,input_shape=(12,),activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')])
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
235/235 [==============================] - 0s 508us/step - loss: 0.6089 - accuracy: 0.6729
Epoch 2/100
235/235 [==============================] - 0s 507us/step - loss: 0.4792 - accuracy: 0.8023
Epoch 3/100
235/235 [==============================] - 0s 507us/step - loss: 0.4429 - accuracy: 0.8069
Epoch 4/100
235/235 [==============================] - 0s 507us/step - loss: 0.4277 - accuracy: 0.8117
Epoch 5/100
235/235 [==============================] - 0s 500us/step - loss: 0.4171 - accuracy: 0.8189
Epoch 6/100
235/235 [==============================] - 0s 511us/step - loss: 0.4078 - accuracy: 0.8231
Epoch 7/100
235/235 [==============================] - 0s 511us/step - loss: 0.3983 - accuracy: 0.8284
Epoch 8/100
235/235 [==============================] - 0s 536us/step - loss: 0.3896 - accuracy: 0.8353
Epoch 9/100
235/235 [==============================] - 0s 740us/step - loss: 0.3818 - accuracy: 0.8416
Epoch 10/100
235/235 [==============================] - 0s 695us/step - l

235/235 [==============================] - 0s 511us/step - loss: 0.3388 - accuracy: 0.8628
Epoch 80/100
235/235 [==============================] - 0s 507us/step - loss: 0.3385 - accuracy: 0.8615
Epoch 81/100
235/235 [==============================] - 0s 506us/step - loss: 0.3386 - accuracy: 0.8623
Epoch 82/100
235/235 [==============================] - 0s 541us/step - loss: 0.3384 - accuracy: 0.8628
Epoch 83/100
235/235 [==============================] - 0s 507us/step - loss: 0.3385 - accuracy: 0.8628
Epoch 84/100
235/235 [==============================] - 0s 524us/step - loss: 0.3384 - accuracy: 0.8631
Epoch 85/100
235/235 [==============================] - 0s 592us/step - loss: 0.3384 - accuracy: 0.8621
Epoch 86/100
235/235 [==============================] - 0s 545us/step - loss: 0.3382 - accuracy: 0.8629
Epoch 87/100
235/235 [==============================] - 0s 507us/step - loss: 0.3383 - accuracy: 0.8613
Epoch 88/100
235/235 [==============================] - 0s 507us/step - loss:

In [14]:
y_p=model.predict(x_test)
y_p[:10]

array([[0.3108533 ],
       [0.36067405],
       [0.17701459],
       [0.0634189 ],
       [0.06571457],
       [0.8520377 ],
       [0.02832195],
       [0.08493018],
       [0.26692262],
       [0.8250638 ]], dtype=float32)

In [15]:
y_pred=[]
for element in y_p:
    if element>0.5:
        y_pred.append(1)
    else: 
        y_pred.append(0)
        

In [16]:
y_pred[:10]

[0, 0, 0, 0, 0, 1, 0, 0, 0, 1]

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1892,   99],
       [ 252,  257]], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score 
ac=accuracy_score(y_test,y_pred)
ac

0.8596

In [19]:
tf.math.confusion_matrix(y_test,y_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1892,   99],
       [ 252,  257]])>

# Thank You !!